import { PCRStructuredData } from '@/types/pcr';

// ─────────────────────────────────────────────────────────────────────────────
// SYSTEM PROMPT — applies to every PCR interaction
// ─────────────────────────────────────────────────────────────────────────────

export const PCR_SYSTEM_PROMPT = `You are a PCR (Project Change Request) drafting assistant for Presidio, a technology solutions company.

YOUR ROLE:
You help Solution Owners draft the narrative sections of a PCR document. You do NOT author document structure, legal boilerplate, section headers, pricing tables, resource tables, or signature blocks. Those are template-locked and handled by the system.

You generate content for these narrative slots:
- CHANGE_SUMMARY: Section 1 — exactly 3 sentences. Sentence 1: what is being added/changed and the team size. Sentence 2: what the platform or deliverable does and the strategic problem it solves. Sentence 3: pricing impact and program phase.
- SOLUTION_APPROACH: Section 1.2 — exactly 2–3 sentences describing the technical problem and the architectural approach that solves it. Do NOT list components or deliverables here — that belongs in SCOPE_CHANGES.
- SCOPE_CHANGES: Section 2.1 — one phase header line followed by a bullet list of specific deliverables. Each bullet is one deliverable, named precisely. No prose paragraphs. No vague descriptions.
- RESOURCE_CHANGES: Section 3.1 — omit this slot entirely. The resource table, deliverables, and engagement length are generated by the system from the SPW data. Do not generate any narrative for this section.
- ASSUMPTION_CHANGES: Section 6.0 — a list of labeled assumption items. Each item must be formatted as: "LABEL: [one or two sentences]". Labels are short noun phrases (e.g., "Team Availability", "PM System Access", "HIPAA Compliance"). Every assumption the SO mentioned must appear as a separate labeled item.

RULES:
- Use formal, professional contract language consistent with the Presidio PCR template.
- Reference the original SOW section numbers where relevant (e.g., "pursuant to Section 2.1").
- Never invent facts, numbers, dates, or roles not provided by the Solution Owner.
- Never include legal clauses, acceptance language, or pricing formulas.
- Keep language concise and approval-ready. Write in complete sentences. Avoid filler phrases.
- Always refer to the client by the name provided.
- When the Solution Owner provides a rich description of the changes, use that description as the primary source. Extract all relevant facts from it — team composition, technical approach, program structure, assumptions, timeline — and weave them into the appropriate narrative slots.
- Omit any slot that has no applicable content. Never generate a slot with placeholder text.
- CRITICAL — LEGAL LANGUAGE: This document is legally binding. Never use vague or hedging language. Specifically prohibited: "among others", "among other things", "etc.", "and so on", "including but not limited to", "such as (when implying an incomplete list)", or any other phrase that implies an open-ended or incomplete enumeration. If you must list items, list them completely and specifically. If you cannot enumerate all items, describe the category without suggesting the list is partial.
- Be specific and exhaustive. Every deliverable, capability, assumption, and resource mentioned by the Solution Owner must be named explicitly.

OUTPUT FORMAT — use these exact labels, one per line, followed by the content:
CHANGE_SUMMARY:
[3 sentences]

SOLUTION_APPROACH:
[2–3 sentences — omit if no solution approach change]

SCOPE_CHANGES:
Phase N – [Phase Name] (Sprints X–Y)
• [Deliverable 1]
• [Deliverable 2]
• [Deliverable N]
[omit if no scope change]

ASSUMPTION_CHANGES:
Label One: [sentence or two].
Label Two: [sentence or two].
[one labeled item per assumption — omit section if no assumptions]

EXTRACTION RULES (during the conversational step, before narrative generation):
- Extract: roles added/removed/changed, resource counts, timeline changes (days/months), scope description, pricing impact, assumptions.
- Present extracted data back as a structured confirmation list so the SO can verify each item.
- Do not draft PCR narrative until the user confirms the extracted data is correct.`;

// ─────────────────────────────────────────────────────────────────────────────
// EXTRACTION PROMPT — used to parse conversational or document input
// ─────────────────────────────────────────────────────────────────────────────

export function buildExtractionPrompt(userInput: string, sowContext?: string): string {
  const sowSection = sowContext
    ? `\n\nSOW CONTEXT (from uploaded SOW PDF):\n${sowContext.slice(0, 3000)}\n`
    : '';

  return `${sowSection}
The Solution Owner has provided the following input describing the changes they need to make to the project:

"${userInput}"

Please extract and confirm the following structured information. Present it as a numbered list so the SO can verify each item:

1. Change types identified (scope / resources / timeline / assumptions / pricing)
2. Resources: For each role mentioned — name the role, whether it is being added, removed, or changed, original allocation (if known from SOW), and new allocation
3. Timeline: Program duration, sprint structure, or any extension or reduction in days/months
4. Scope: A 1–2 sentence summary of the scope change and the technical platform or deliverable involved
5. Pricing: Zero-cost change, or estimated impact (if mentioned)
6. Assumptions: Any new or changed assumptions, dependencies, constraints, or external requirements mentioned

If any item is unclear or missing, ask a specific clarifying question.
Do NOT draft any PCR narrative yet — only extract and confirm the structured data.`;
}

// ─────────────────────────────────────────────────────────────────────────────
// NARRATIVE GENERATION PROMPT — used after data is confirmed in Step 3
// ─────────────────────────────────────────────────────────────────────────────

export function buildNarrativePrompt(
  data: PCRStructuredData,
  conversationHistory?: Array<{ role: 'user' | 'assistant'; content: string }>
): string {
  const priorPcrText = data.priorPcrCount > 0
    ? `There ${data.priorPcrCount === 1 ? 'is' : 'are'} ${data.priorPcrCount} prior PCR${data.priorPcrCount === 1 ? '' : 's'} on this engagement.`
    : 'This is the first PCR on this engagement.';

  // Detailed resource list including discipline, theatre, rates, and allocation from SPW
  const resourceSummary = data.resources.length > 0
    ? data.resources.map((r) => {
        const discipline = r.discipline ? r.discipline.replace(/_/g, ' ') : '';
        // r.role may already include theatre as a parenthetical suffix; only append separately if not already present
        const theatre = r.deliveryTheatre && !r.role.includes(r.deliveryTheatre) ? ` (${r.deliveryTheatre})` : '';
        const rate = r.discountedRate && r.discountedRate > 0
          ? `$${r.discountedRate}/hr discounted`
          : r.listRate && r.listRate > 0
          ? `$${r.listRate}/hr list rate`
          : 'zero-cost';
        const disciplineStr = discipline && discipline !== r.role && !r.role.startsWith(discipline) ? `, ${discipline}` : '';
        return `- ${r.role}${theatre}${disciplineStr}: ${r.action.toUpperCase()} | ${r.newAllocation || 'TBD'} | ${rate}`;
      }).join('\n')
    : 'No resource changes specified.';

  const timelineText = data.timelineExtensionDays
    ? `Timeline extension: ${data.timelineExtensionDays} days${data.newEndDate ? `, new end date ${data.newEndDate}` : ''}.`
    : 'No timeline change specified.';

  const pricingText = data.pricingChange.isZeroCost
    ? 'This is a zero-cost change (no pricing impact).'
    : `Pricing changes from ${data.pricingChange.originalTotal ?? 'original total'} to ${data.pricingChange.newTotal ?? 'new total'}.${data.pricingChange.notes ? ' ' + data.pricingChange.notes : ''}`;

  const changeTypesList = data.changeTypes.length > 0
    ? data.changeTypes.join(', ')
    : 'scope, resources';

  // Include the SO's original description from the conversation — this is the richest source
  // of truth for what the platform does, team structure, assumptions, and technical approach.
  const soDescription = conversationHistory
    ? conversationHistory
        .filter((m) => m.role === 'user')
        .map((m) => m.content)
        .join('\n\n')
    : '';

  const soDescriptionSection = soDescription
    ? `\nSOLUTION OWNER DESCRIPTION (use this as the primary source for all narrative content):\n"""\n${soDescription}\n"""\n`
    : '';

  const sowContextSection = data.sowContext
    ? `\nSOW CONTEXT (background from the original Statement of Work):\n${data.sowContext.slice(0, 2000)}\n`
    : '';

  return `The Solution Owner has confirmed the following structured data for the PCR. Generate all applicable narrative sections now using the information below. The Solution Owner's description is the authoritative source — extract team composition, technical approach, program structure, assumptions, and any other relevant details from it.
${soDescriptionSection}
PROJECT: ${data.projectName}
CLIENT: ${data.clientName}
SOW DATE: ${data.sowDate}${data.sowId ? `\nSOW ID: ${data.sowId}` : ''}
${priorPcrText}

CHANGE TYPES: ${changeTypesList}

CONFIRMED RESOURCE CHANGES (from uploaded SPW):
${resourceSummary}

TIMELINE: ${timelineText}

PRICING: ${pricingText}
${sowContextSection}
Generate ALL applicable narrative sections using the Solution Owner's description as the primary source. Use the exact output format from your instructions. Do not add preamble or commentary — output only the labeled slots.

CHANGE_SUMMARY: Exactly 3 sentences. (1) What is being added and team size. (2) What the platform does and the strategic problem it solves for the client. (3) Pricing impact and program phase name.

SOLUTION_APPROACH: 2–3 sentences only. Describe the technical problem caused by the current state and the architectural approach that solves it. Do NOT list components or deliverables here.

SCOPE_CHANGES: One phase header line ("Phase N – [Name] (Sprints X–Y)") followed by a bullet list using "•" as the bullet character. One bullet per deliverable, named precisely as the SO described it. No prose paragraphs.

ASSUMPTION_CHANGES: Each assumption on its own line, formatted as "Label: sentence or two." Use the exact labels and facts the SO provided. One labeled item per distinct assumption. Do not combine assumptions.`;
}

// ─────────────────────────────────────────────────────────────────────────────
// NARRATIVE PARSER — extracts labeled slots from LLM output
// ─────────────────────────────────────────────────────────────────────────────

export function parseNarrativeResponse(response: string): {
  changeSummary?: string;
  solutionApproachChanges?: string;
  scopeChanges?: string;
  resourceRationale?: string;
  assumptionChanges?: string;
} {
  // Match each label: capture everything after "LABEL:\n" until the next all-caps label or end of string
  function extract(label: string): string | undefined {
    const regex = new RegExp(`${label}:\\s*([\\s\\S]*?)(?=\\n[A-Z_]+:|$)`, 'i');
    const match = response.match(regex);
    return match?.[1]?.trim() || undefined;
  }

  return {
    changeSummary: extract('CHANGE_SUMMARY'),
    solutionApproachChanges: extract('SOLUTION_APPROACH'),
    scopeChanges: extract('SCOPE_CHANGES'),
    resourceRationale: extract('RESOURCE_CHANGES'),
    assumptionChanges: extract('ASSUMPTION_CHANGES'),
  };
}
